### ISSUE TITLE
Gnome Garude (Arch) wont boot if service is enabled

### ISSUE THREAD

**Issue by Juschwy** [ldrahnik/asus-stylus-driver#13]
I havent really found any error logs yet, but if the service is enabled, Garuda is stuck at the blinking underline (when normally gnome shell would start).
Workaround is to start the service after boot is finished.

**Comment by ldrahnik** [comment]
Hi, thank you for creating an issue but unfortunatelly I can do nothing without boot logs. I mean detecting origin problem. Workaround for you may be add start delay few seconds, 5/10 to systemctl service. It should help. Can be reopened.
