### ISSUE TITLE
Zenbook 13 stylus simply not working.

### ISSUE THREAD

**Issue by Nycter** [ldrahnik/asus-stylus-driver#3]
So basically before the switch to arch my stylus worked fine.  have set bluetooth to run (i dont know if that has anything to do with it), but still my stylus doesn't show any signs of doing anything. I have run `LOG=DEBUG sudo -E ./asus_stylus.py` and  this is the output

```DEBUG:Pen:Detect stylus from N: Name="ELAN7003:00 03F1:2D4A Stylus"
DEBUG:Pen:Set stylus device id 9 from S: Sysfs=/devices/pci0000:00/0000:00:15/i2c_designware.0/12c-9/ELAN003:00 03F1:2D4A.0001/input/input24
DEBUG:Pen:Set stylus id 9 from H=Handlers=event9 mouse1```

**Comment by ldrahnik** [comment]
Hello,
thank you for creating an issue. 

I now use Ubuntu 20.04 and stylus has default driver but only buttons does not work properly, so this driver is atm only complementary as is even mentioned in the description. 

Run command `libinput debug-events` and for example go with stylus in hand closer to laptop display, any events occur?

**Comment by ldrahnik** [comment]
Closed for issue owner inactivity, can be reopened.
