### ISSUE TITLE
Breaks PopOS, VanillaOS and Fedora

### ISSUE THREAD

**Issue by Tahinli** [ldrahnik/asus-stylus-driver#4]
I don't know why but, i tried these distros. When i install, there is no problem, but after reboot can't see my desktop. It stucks on login. These three are just fresh install, i just did their updates and followed github processes. I could login with ctrl+alt+F buttons to terminal and reach my files but can not see desktop.

[Information]

Every distro has gnome.
PoP and Vanilla is 22.04 Ubuntu base i think.
Fedora Workstation 38.

I have Asus Zenbook UM3402YA
Ryzen 5 5625U

**Comment by ldrahnik** [comment]
@Tahinli Hello, thank you for creating an issue. Unfortunatelly without logs I can not help you.

**Comment by Tahinli** [comment]
> @Tahinli Hello, thank you for creating an issue. Unfortunatelly without logs I can not help you.

in fedora i couldn't even login to shell. I will install PoP in a second. In this time can you give me some tricks about how can i send you logs

**Comment by Tahinli** [comment]
Okay i am ready to debug.

Installed Pop OS
sudo apt update then upgrade
Rebooted
Followed Github recipe
--- sudo apt install libevdev2 python3-libevdev git
--- git clone https://github.com/asus-linux-drivers/asus-stylus-driver
--- cd asus-stylus-driver
--- sudo ./install.sh
then in setup i selected 1 which is default.py.
i tried and there is no problem
Then reboot
Can not see my desktop but able to login shell with ctrl+alt+F2

Now, I dont know how to debug well. If you guide me, i will try

**Comment by Tahinli** [comment]
Here is service statuses

![1](https://github.com/asus-linux-drivers/asus-stylus-driver/assets/96421894/e30a1363-df31-42a7-abb7-70dfd4fa551a)
![2](https://github.com/asus-linux-drivers/asus-stylus-driver/assets/96421894/c8fa0cb5-1add-4fdc-accd-375fa123ddc1)

**Comment by ldrahnik** [comment]
@Tahinli Attach here systems service log please

**Comment by ldrahnik** [comment]
@Tahinli Does use Pop X11?

**Comment by Tahinli** [comment]
> @Tahinli Does use Pop X11?

yes

**Comment by Tahinli** [comment]
> @Tahinli Attach here systems service log please

how ?

**Comment by ldrahnik** [comment]
@Tahinli `cat /var/log/asus_stylus-driver/error.log`

**Comment by ldrahnik** [comment]
@Tahinli Also current x11 log please `cat /var/log/Xorg.0.log`

**Comment by Tahinli** [comment]
there was no file in /var/log about xorg afaik. so i'm sending ~/.local/share/xorg/Xorg.1.log

[error.log](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11860414/error.log)
[Xorg.1.log](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11860415/Xorg.1.log)

**Comment by ldrahnik** [comment]
@Tahinli Could you attach also log of systemctl `gdm.service`, `cat /lib/systemd/system/gdm.service`, find line `StandardError` and do cat also and attach here please

**Comment by Tahinli** [comment]
github don't support service file extention thats why i added txt.
and there is no StandardError in this.

[gdm.service.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11860453/gdm.service.txt)

**Comment by ldrahnik** [comment]
@Tahinli Well, log is not explicitely defined, so please try find yourself, there will be written why it does not starts `/var/log/gdm` maybe

**Comment by Tahinli** [comment]
Okay  i did:  journalctl -u gdm.service | tee ~/Desktop/a.txt

I think this will help

[a.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11860472/a.txt)

**Comment by ldrahnik** [comment]
@Tahinli Attach please entire journalctl booting log

**Comment by Tahinli** [comment]
I rebooted then did: journalctl | tee ~/Desktop/b.txt

[b.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11860512/b.txt)

**Comment by ldrahnik** [comment]
@Tahinli I would try to install this driver but stop systemctl service from autoloading during booting, question is restart and log in OK? So installed packages are fine for gnome, only starting service is somehow a problem. Can you confirm, please? 

Comment out these lines in `install.sh`:

```
systemctl enable asus_stylus

if [[ $? != 0 ]]
then
	echo "Something gone wrong while enabling asus_stylus.service"
	exit 1
else
	echo "Asus stylus service enabled"
fi

systemctl restart asus_stylus
if [[ $? != 0 ]]
then
	echo "Something gone wrong while enabling asus_stylus_numpad.service"
	exit 1
else
	echo "Asus stylus service started"
fi
```

I would do the first restart without manually starting and testing before, second one with manually starting (`systemctl start`), using stylus and then stopping (`systemctl stop`) and restart. Second restart would confirm running code do not change something in the system (x11 settings etc)

**Comment by Tahinli** [comment]
When i stop asus stylus service. it logged in without problem.

sudo systemctl stop asus_stylus.service

After logged in I just started service again

sudo systemctl start --now asus_stylus.service

then there is no problem

i would suggest that, we should modify installation script to enable service after logged in, not in start.

I can confirm that you are right.

**Comment by Tahinli** [comment]
I will do some changes, and try. If i can solve, i will try to Pull Request.

**Comment by ldrahnik** [comment]
@Tahinli I would experiment myself with not running driver code in service: `ExecStart=/usr/bin/env python3 /usr/share/asus_stylus-driver/asus_stylus.py $LAYOUT`, removing `ExecStartPre=/bin/sleep 2`, I would check what is set up as `default.target` in your system

**Comment by Tahinli** [comment]
> @Tahinli I would experiment myself with not running driver code in service: `ExecStart=/usr/bin/env python3 /usr/share/asus_stylus-driver/asus_stylus.py $LAYOUT`, removing `ExecStartPre=/bin/sleep 2`, I would check what is set up as `default.target` in your system

Sorry, I couldn't understand clearly.

**Comment by ldrahnik** [comment]
@Tahinli I would change these lines in service file, then enable service and then restart - look whether Is booting still a problem

**Comment by Tahinli** [comment]
Second part is okay, i will delete

> ExecStartPre=/bin/sleep 2

but what should i do for first part ? 

> ExecStart=/usr/bin/env python3 /usr/share/asus_stylus-driver/asus_stylus.py $LAYOUT

**Comment by ldrahnik** [comment]
@Tahinli empty command e.g. `/bin/sh -c ' '`

**Comment by Tahinli** [comment]
Here is my service file and, rebooted successfully but driver isn't working as you know.

[c.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870155/c.txt)

**Comment by Tahinli** [comment]
Here is my systemctl status output

[d.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870193/d.txt)

**Comment by ldrahnik** [comment]
@Tahinli Now I would try again with Python script in service ExecStart row but with empty Python file so will know problem Is calling python script or python script itself

**Comment by Tahinli** [comment]
Here is my service file
[e.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870346/e.txt)

and my python code is 

> print("hi")

and it rebooted successfully

**Comment by Tahinli** [comment]
maybe some infinite loops prevent to start system,

because i edited code

> print("hi")
> while(1):
>> print("hello")

then my system is stuck again

**Comment by ldrahnik** [comment]
@Tahinli Remove everything below line with comment Start monitoring the stylus and try again

**Comment by ldrahnik** [comment]
@Tahinli Ok, in case infinity cycle does a stuck I would check how are written systemctl services which run aswell python code in gnome, can you?

**Comment by Tahinli** [comment]
Here are my outputs
[f.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870484/f.txt)
[g.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870485/g.txt)

Driver is working and system is rebooted successfully.

**Comment by ldrahnik** [comment]
@Tahinli Good to know :) but would be great to know which line is a problem.

I would try to use `multi-user.target` like this

```
[Unit]
After=multi-user.target

[Install]
WantedBy=multi-user.target
```

**Comment by Tahinli** [comment]
> @Tahinli Good to know :) but would be great to know which line is a problem.
> 
> I would try to use `multi-user.target` like this
> 
> ```
> [Unit]
> After=multi-user.target
> 
> [Install]
> WantedBy=multi-user.target
> ```

here are outputs

[h.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870643/h.txt)
[i.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11870644/i.txt)

problem is
login screen is able to come, but after login we see black screen

when i switch tty2(ctrl+alt+f2) my desktop opens automatically without logging or starting gdm. driver service is running but driver isn't working.

it's a bit strange

tty1= Broken after logging in
tty2= logging in and starts desktop automatically without any touching
tty3-4-5-6= normally waits for user login

**Comment by Tahinli** [comment]
Okay I find, which line causes problem.

>  	StandardInput=tty-force

This service code is working properly and there is no reboot problem for me.

    [Unit]
	Description=Asus Stylus Handler
	
	[Service]
	Type=simple
	ExecStart=/usr/bin/env python3 /usr/share/asus_stylus-driver/asus_stylus.py $LAYOUT
	#StandardInput=tty-force
	StandardOutput=append:/var/log/asus_stylus-driver/error.log
	StandardError=append:/var/log/asus_stylus-driver/error.log
	TimeoutSec=5
	Restart=on-failure
	# For some operating systems with boot failure, adding this following property might resolve the issue  
	ExecStartPre=/bin/sleep 2
	
	[Install]
	WantedBy=default.target

I uncommented them line by line and check, if driver is working properly and reboot successfully. This is the result finally.

**Comment by ldrahnik** [comment]
@Tahinli But when you comment out `ExecStart` then is driver not started

**Comment by ldrahnik** [comment]
@Tahinli I removed from service code pre start sleep there is no reason do that

**Comment by Tahinli** [comment]
> @Tahinli But when you comment out `ExecStart` then is driver not started

sorry I mistyped. now i corrected , just need to comment or delete Standart input line.

**Comment by Tahinli** [comment]
> @Tahinli I removed from service code pre start sleep there is no reason do that

also driver works without it, i don't know what is the result of this line

**Comment by Tahinli** [comment]
This one is working pretty well for me.

> 
> [Unit]
> Description=Asus Stylus Handler
> 
> [Service]
> Type=simple
> ExecStart=/usr/bin/env python3 /usr/share/asus_stylus-driver/asus_stylus.py $LAYOUT
> StandardOutput=append:/var/log/asus_stylus-driver/error.log
> StandardError=append:/var/log/asus_stylus-driver/error.log
> TimeoutSec=5
> Restart=on-failure
> 
> [Install]
> WantedBy=default.target

**Comment by ldrahnik** [comment]
@Tahinli Could you please confirm the same problem has driver [asus-numberpad](https://github.com/asus-linux-drivers/asus-numberpad-driver), might be solution for similar problem reported for Gnome [here](https://github.com/asus-linux-drivers/asus-numberpad-driver/issues/123)

**Comment by ldrahnik** [comment]
@Tahinli make pull request here if you want I will merge it with change on line #StandardInput=tty-force

**Comment by Tahinli** [comment]
> @Tahinli Could you please confirm the same problem has driver [asus-numberpad](https://github.com/asus-linux-drivers/asus-numberpad-driver), might be solution for similar problem reported for Gnome [here](https://github.com/asus-linux-drivers/asus-numberpad-driver/issues/123)

i will check

**Comment by Tahinli** [comment]
> @Tahinli make pull request here if you want I will merge it with change on line #StandardInput=tty-force

I would be pretty happy, let me prepare

**Comment by ldrahnik** [comment]
@Tahinli Pull request for [numberpad](https://github.com/asus-linux-drivers/asus-numberpad-driver) is welcome too but please test it first, check logs so we can be sure it is fix

**Comment by Tahinli** [comment]
> @Tahinli Pull request for [numberpad](https://github.com/asus-linux-drivers/asus-numberpad-driver) is welcome too but please test it first, check logs so we can be sure it is fix

I freshly installed Pop OS again for clean test. I will try.

**Comment by ldrahnik** [comment]
I close this issue as solved, please continue in numberpad [here](https://github.com/asus-linux-drivers/asus-numberpad-driver/issues/123) or you can write me an e-mail with non issue related

**Comment by ldrahnik** [comment]
@Tahinli Wasnt this bug reported because you had installed also broken numpad driver? Stylus driver would start fine alone? Without removing row `tty-force` StandardInput?

**Comment by Tahinli** [comment]
> @Tahinli Wasnt this bug reported because you had installed also broken numpad driver? Stylus driver would start fine alone? Without removing row `tty-force` StandardInput?

It wasnt working, even it was alone. If you want i can try again with fresh install, when i am available

**Comment by ldrahnik** [comment]
@Tahinli Yes, please try to take as an example working number pad driver service, different is what I see line `User=%i`, not removed `StandardInput=tty-force` and `WantedBy=graphical.target`, change all of these and it should be working I guess.

**Comment by Tahinli** [comment]
okay i'm here, and here is my service file. 
I got files from 

https://github.com/asus-linux-drivers/asus-stylus-driver/tree/24f0fcebbad19d2d0de1696049fb9793ca49af61
this commit

[asus_stylus.service.txt](https://github.com/asus-linux-drivers/asus-stylus-driver/files/11923109/asus_stylus.service.txt)

i installed and rebooted.

no black screen issue.

I can swear on that, it wasn't working, few days ago.

maybe you changed something in this commit that causes bug earlier, or gnome got some update. because when i was saying standartinput was breaking system. I tried it many times.

**Comment by ldrahnik** [comment]
@Tahinli Maybe that sleep 2s, anyway would be interesting service like this would cause a black screen. Reverted. Thank you for test :)

**Comment by Tahinli** [comment]
Bonus fact: Rnote (https://flathub.org/apps/com.github.flxzt.rnote) was behaving asus stylus pen like a mouse with your driver. now it accepted that it's a pen. Maybe this is about this changes.
https://github.com/asus-linux-drivers/asus-stylus-driver/commit/24f0fcebbad19d2d0de1696049fb9793ca49af61
