### ISSUE TITLE
Unsupported Zenbook DUO

### ISSUE THREAD

**Issue by Safenein** [ldrahnik/asus-stylus-driver#9]
There is two issue when using a Zenbook DUO (Zenbook UX8402ZE_UX8402ZE).

Stylus is *usable* on the main screen but unrecognized when using second one.
No debug output when using on the bottom screen.

Moreover, the input is mapped on the two screen united (when using on main screen, the bottom is mapped on the second screen).

Please, tell me how can I help you getting more information to fix the driver.

- [x] Map to monitor
- [x] Work on multiple monitor

(used on Linux ******* 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux)

**Comment by ldrahnik** [comment]
Hello there,
thank you for creating an issue. What is the output of command `$ sudo libinput debug-events` when is stylus used on the second screen? (please post entire output)

**Comment by Safenein** [comment]
Here is the output without useless and unrelated lines:
```
-event12  DEVICE_ADDED            ELAN9008:00 04F3:2F29             seat0 default group5  cap:t  size 300x188mm ntouches 10 calib
-event22  DEVICE_ADDED            ELAN9008:00 04F3:2F29 Stylus      seat0 default group5  cap:T  size 310x194mm calib
-event15  DEVICE_ADDED            ASUE1212:00 04F3:3233 Mouse       seat0 default group6  cap:p left scroll-nat scroll-button
-event16  DEVICE_ADDED            ASUE1212:00 04F3:3233 Touchpad    seat0 default group6  cap:pg  size 51x75mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on dwtp-on
-event17  DEVICE_ADDED            ELAN9009:00 04F3:2F2A             seat0 default group7  cap:t  size 321x96mm ntouches 5 calib
-event20  DEVICE_ADDED            ELAN9009:00 04F3:2F2A Stylus      seat0 default group7  cap:T  size 308x93mm calib
-event21  DEVICE_ADDED            ELAN9009:00 04F3:2F2A Touchpad    seat0 default group7  cap:pg  size 321x96mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on dwtp-on
-event7   DEVICE_ADDED            Asus WMI hotkeys                  seat0 default group8  cap:k
-event20  TABLET_TOOL_PROXIMITY   +4294967.295s         286.22*/76.25*  tilt: 0.00*/0.00*       pressure: 0.00* pen      (0, id 0) proximity-in         axes:pt btn:S
 event20  TABLET_TOOL_PROXIMITY   +0.050s               286.22/76.25    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out
 event20  TABLET_TOOL_PROXIMITY   +0.166s               285.42*/75.97*  tilt: 0.00*/0.00*       pressure: 0.00* pen      (0, id 0) proximity-in         axes:pt btn:S
 event20  TABLET_TOOL_PROXIMITY   +0.216s               285.42/75.97    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out
 event20  TABLET_TOOL_PROXIMITY   +0.409s               285.03*/75.97*  tilt: 0.00*/0.00*       pressure: 0.00* pen      (0, id 0) proximity-in         axes:pt btn:S
 event20  TABLET_TOOL_PROXIMITY   +0.459s               285.03/75.97    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out
 event20  TABLET_TOOL_PROXIMITY   +0.584s               284.80*/75.97*  tilt: 0.00*/0.00*       pressure: 0.00* pen      (0, id 0) proximity-in         axes:pt btn:S
 event20  TABLET_TOOL_PROXIMITY   +0.634s               284.80/75.97    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out
 event20  TABLET_TOOL_PROXIMITY   +1.085s               284.80*/75.89*  tilt: 0.00*/0.00*       pressure: 0.00* pen      (0, id 0) proximity-in         axes:pt btn:S
 event20  TABLET_TOOL_PROXIMITY   +1.135s               284.80/75.89    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out
 event20  TABLET_TOOL_PROXIMITY   +1.160s               284.80*/75.81*  tilt: 0.00*/0.00*       pressure: 0.00* pen      (0, id 0) proximity-in         axes:pt btn:S
 event20  TABLET_TOOL_AXIS        +1.185s               284.80/75.78*   tilt: 0.00/0.00 pressure: 0.00
 event20  TABLET_TOOL_AXIS        +1.190s               284.80*/75.57*  tilt: 7.25*/10.50*      pressure: 0.00*
 event20  TABLET_TOOL_TIP         +1.278s               284.91/75.10    tilt: 25.16*/38.16*     pressure: 0.05* down
 event20  TABLET_TOOL_AXIS        +1.281s               284.89*/75.08*  tilt: 25.16/38.16       pressure: 0.05
 event20  TABLET_TOOL_AXIS        +1.295s               284.84*/75.05   tilt: 25.23/38.23       pressure: 0.07*
 event20  TABLET_TOOL_AXIS        +1.299s               284.83*/75.05   tilt: 25.25*/38.25*     pressure: 0.10*
 event20  TABLET_TOOL_AXIS        +1.926s               283.08*/74.71*  tilt: 26.29/39.29       pressure: 0.01*
 event20  TABLET_TOOL_TIP         +1.930s               283.09*/74.75*  tilt: 0.00*/0.00*       pressure: 0.00* up
 event20  TABLET_TOOL_PROXIMITY   +1.980s               283.09/74.75    tilt: 0.00/0.00 pressure: 0.00  pen      (0, id 0) proximity-out
```

I tried to keep as much as possible useful lines. Tell me is some are missing and you need it.

**Comment by Safenein** [comment]
Ok I got a workaround by using threads (I think performances would be ok since you don't use two stylus at the same time).

The code is not clean. If this is good enough for you I'll clean it and PR.

There is still the issue with wrongly mapped touchscreen but this is a first step.

See https://github.com/Safenein/asus-stylus-driver

**Comment by ldrahnik** [comment]
@Safenein Hm, looks like the same regex should work. Agree with you, the first necessary step. I will definitely merge your PR. What has to be IMHO modified to complete and merge is thread and file descriptor cleanup via `thread.join()` and `fd_t.close()`.

**Comment by Safenein** [comment]
I didn't change the regex, I just let the program read all valid input instead of exiting on first occurrence.

Since you used `while True:`, I thought that would not be really useful to join thread and just let get terminated by python (let it handle it). It it doesn't suit you, I'm afraid I cannot help you for now, I have no idea how to handle signal in python.

**Comment by ldrahnik** [comment]
@Safenein No problem, I will eventually change it. What I do not understand is your problem, using the command `$ sudo libinput debug-events` you get events from the stylus on both screens? or not? Which virtual device (id) is associated (from the previous output) to second screen and which one to main?

**Comment by Safenein** [comment]
Can you take another look to the fork (https://github.com/Safenein/asus-stylus-driver) when you get time?

I do have two devices. I'm using Hyprland and I found a parameter to map the output to one monitor at a time so this issue is fixed (in config file "device:\<name\> { output = \<monitor\> }").

On the fork I did, I renamed some variables and refactor to make things I did clearer. SIGINT is supported by using process instead of threads (so you can use multiple stylus on multiple screen at the same time I guess).

But by doing all of this, I have a new issue and I can't figure what this is. The input on the main monitor (only this one) are doubled. So it kinda defeat the whole point of the driver :/ because it mess up the behavior of the buttons.

**Comment by ldrahnik** [comment]
@Safenein Understand, the point why I created this driver was my stylus buttons send nothing useful so I was not afraid of doubling key events. Do you use X11 or Wayland? In X11 I have experience with grabbing only specifing key from virtual device so then can be send only replaced key/s because grabbing means exclusive access. Prototype of code (which works) Is here https://github.com/asus-linux-drivers/asus-stylus-driver/issues/7 but I have not had time to implement it yet unfortunatelly. I personally do not use Wayland so in this case I would have to do research but I guess something like grabbing depends on used compositor and cannot be done universally like on X11 via X11 Python lib.

**Comment by ldrahnik** [comment]
@Safenein In short, without grabbing virtual device (as the code of this driver works now) can be listened key used by other drivers, offered solution of grabbing means exclusive access to virtual device (can ve specified only for array of keys (rebinded for example as this driver do)) so any other driver will not even receive specified event about pushing button. I hope I clarified it and understood correctly you mean by doubling this problem.

**Comment by Safenein** [comment]
I am indeed using Wayland (I may open a new issue soon but I dont know if et can be fixed in this repo).

In fact I have no idea what I'm doing as I never developed drivers of any kind. I hope I'll find out what is wrong and thank you for taking time to explain. 

I'll try new things soon so maybe you won't have to spend time on this. Your original software is working fine on main screen so I hope I'll figure what is happening. 

Last question, are you OK with the way I refactored the code?

**Comment by ldrahnik** [comment]
@Safenein Looks clean, please make PR, I will test it for sure aswell and merge it. As you wrote code added by you Is usefull in case using more stylus devices at one time.

**Comment by Safenein** [comment]
I finally fixed the double input issue. When I was putting everything in arrays to make it work on multiple inputs and as I had no idea what I was doing, I forgot to duplicate udev interface so each input get one udev interface.

Everything should be fine in #10

**Comment by ldrahnik** [comment]
@Safenein I put two comments on your PR, I will check further later
